---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: helloworld
        image: "ironcore864/go-hello-http:{{ default .Chart.AppVersion .Values.image.tag }}"
        ports:
        - containerPort: 8080
