apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  annotations:
    linkerd.io/inject: enabled
  labels:
    app: helloworld
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: "ironcore864/go-hello-http:{{ .Chart.AppVersion }}"
        ports:
        - containerPort: 8080
