---
kind: Service
apiVersion: v1
metadata:
  name: helloworld-v1
spec:
  selector:
    app: helloworld
    version: v1
  ports:
    - port: 80
      targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: helloworld-v2
spec:
  selector:
    app: helloworld
    version: v2
  ports:
    - port: 80
      targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: helloworld
spec:
  selector:
    app: helloworld
  ports:
    - port: 80
      targetPort: 8080
