{{- if .Values.trafficSplit -}}
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: helloworld-canary
spec:
  service: helloworld
  backends:
    - service: helloworld
      weight: 50
    - service: helloworld-tiexin2
      weight: 50
{{- end -}}
