---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: helloworld-canary
spec:
  service: helloworld
  backends:
    - service: helloworld-v1
      weight: 90
    - service: helloworld-v2
      weight: 10
