{{- if .Values.trafficSplit -}}
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: helloworld-canary
spec:
  service: helloworld
  backends:
    - service: helloworld
      weight: 20
    - service: helloworld-tiexin2
      weight: 40
    - service: helloworld-use1
      weight: 40
{{- end -}}
