---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-use1
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://022FA4C522D527B0C2DCB10D2BF4C30B.gr7.us-east-1.eks.amazonaws.com
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
      - values.tiexin2.yaml
    path: go-hello-http
    repoURL: https://github.com/ironcore864/gitops-argocd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

